CREATE TABLE Calificacion (id int4 NOT NULL, Inmuebleid int4, Clienteid int4, Personalid int4, calificacion float8, fecha_calificacion date, comentario varchar(255), PRIMARY KEY (id));
COMMENT ON TABLE Calificacion IS 'Tabla donde se almacenará las calificaciones dada por los clientes: al inmueble, al servicio y al agente.';
COMMENT ON COLUMN Calificacion.id IS 'Id de la calificación';
COMMENT ON COLUMN Calificacion.calificacion IS 'Calificación cuantitativa otorgada';
COMMENT ON COLUMN Calificacion.fecha_calificacion IS 'Fecha en la que se otorgó la calificación';
COMMENT ON COLUMN Calificacion.comentario IS 'Comentario dejado por el cliente';
CREATE TABLE Cita (id int4 NOT NULL, Servicioid int4 NOT NULL, Inmuebleid int4, fecha_solicitud date, fecha_aprobacion date, fecha_atendida date, comentario varchar(255), estatus char(255), Clienteid int4, Personalid int4, TipoCitaid int4, PRIMARY KEY (id));
COMMENT ON TABLE Cita IS 'Tabla para almacenar las citas dependiendo del tipo de cita. Se manejan según estatus (solicitud, en proceso, cancelada, finalizada, etc.)';
COMMENT ON COLUMN Cita.id IS 'Id de la cita';
COMMENT ON COLUMN Cita.fecha_solicitud IS 'Fecha en que se solicitó la cita';
COMMENT ON COLUMN Cita.fecha_aprobacion IS 'Fecha en que fue aprobada la solicitud de cita';
COMMENT ON COLUMN Cita.fecha_atendida IS 'Fecha en la cual la cita fue atendida';
COMMENT ON COLUMN Cita.comentario IS 'Comentarios referente a la cita';
COMMENT ON COLUMN Cita.estatus IS 'Estatus de la cita: solicitud, en proceso, cancelada, finalizada, etc.';
CREATE TABLE Cliente (Sucursalid int4, id int4 NOT NULL, identificacion varchar(255), fecha_nacimiento date, nombres varchar(255), apellidos varchar(255), telefono varchar(255), correo varchar(255), banco_nombre varchar(255), banco_cuenta varchar(255), sexo char(255), estatus char(255), TipoClienteid int4, PRIMARY KEY (id));
COMMENT ON TABLE Cliente IS 'Tabla donde se almacenarán los clientes suscriptos a la inmobiliaria. Tanto un propietario como un cliente dispuesto a comprar/alquilar';
COMMENT ON COLUMN Cliente.id IS 'Id del cliente';
COMMENT ON COLUMN Cliente.identificacion IS 'Identificación del cliente: rif o cédula';
COMMENT ON COLUMN Cliente.fecha_nacimiento IS 'Fecha de nacimiento del cliente';
COMMENT ON COLUMN Cliente.nombres IS 'Nombres del cliente';
COMMENT ON COLUMN Cliente.apellidos IS 'Apellidos del cliente';
COMMENT ON COLUMN Cliente.telefono IS 'Teléfono del cliente';
COMMENT ON COLUMN Cliente.correo IS 'Correo del cliente';
COMMENT ON COLUMN Cliente.banco_nombre IS 'Nombre del banco que tiene el cliente';
COMMENT ON COLUMN Cliente.banco_cuenta IS 'Número de cuenta del banco del cliente';
COMMENT ON COLUMN Cliente.sexo IS 'Sexo del cliente: (M)asculino o (F)emenino';
COMMENT ON COLUMN Cliente.estatus IS 'Estatus del cliente';
CREATE TABLE Contrato (id int4 NOT NULL, Clienteid int4, nro_folio varchar(255), fecha_elaboracion date, fecha_firma date, estatus char(255), Personalid int4, PRIMARY KEY (id));
COMMENT ON TABLE Contrato IS 'Tabla donde se almacenarán los contratos que están ligados a un cliente y un inmueble, el cual trae el servicio (compra, venta, alquiler,etc)';
COMMENT ON COLUMN Contrato.id IS 'Id del contrato';
COMMENT ON COLUMN Contrato.nro_folio IS 'Identificador que usa la inmobiliaria para cada contrato';
COMMENT ON COLUMN Contrato.fecha_elaboracion IS 'Fecha de elaboración del contrato';
COMMENT ON COLUMN Contrato.fecha_firma IS 'Fecha en la cual fue firmado el contrato por el cliente';
COMMENT ON COLUMN Contrato.estatus IS 'Estatus del contrato: en proceso, vigente, vencido, en renovación, etc.';
CREATE TABLE Especificaciones (id int4 NOT NULL, TipoEspecificacionid int4, nombre varchar(255), descripcion varchar(255), PRIMARY KEY (id));
COMMENT ON TABLE Especificaciones IS 'Especificaciones (características) que puede tener un inmueble';
COMMENT ON COLUMN Especificaciones.id IS 'ID de la especificación';
COMMENT ON COLUMN Especificaciones.nombre IS 'Nombre de la especificación';
COMMENT ON COLUMN Especificaciones.descripcion IS 'Descripción de la especificación';
CREATE TABLE EspecificacionesPorInmueble (Inmuebleid int4 NOT NULL, Especificacionesid int4 NOT NULL, cantidad int4, PRIMARY KEY (Inmuebleid, Especificacionesid));
COMMENT ON TABLE EspecificacionesPorInmueble IS 'Tabla intermedia que relaciona las especificaciones por cada inmueble';
COMMENT ON COLUMN EspecificacionesPorInmueble.cantidad IS 'Cantidad de la especificación si así lo requiere (cantidad de baños, cuartos, pisos, etc)';
CREATE TABLE Funciones (id int4 NOT NULL, nombre varchar(255), id_funcion_padre int4, PRIMARY KEY (id));
COMMENT ON TABLE Funciones IS 'Funciones que se pueden realizar en el sistema: registrar clientes, ver contratos, visualizar reportes, etc.

Relación recursiva para casos de funciones anidadas. Gestión Clientes -> registrar, modificar, etc.';
COMMENT ON COLUMN Funciones.id IS 'Id de la función';
COMMENT ON COLUMN Funciones.nombre IS 'Nombre de la función';
CREATE TABLE FuncionesPorRol (Rolid int4, Funcionesid int4, estatus char(255));
COMMENT ON TABLE FuncionesPorRol IS 'Funciones que tiene asignado un rol en particular. El rol root tiene todas las funciones, por ejemplo.';
COMMENT ON COLUMN FuncionesPorRol.estatus IS 'Estatus de la función en el rol';
CREATE TABLE Inmobiliaria (id int4 NOT NULL, nombre varchar(255), mision varchar(255), vision varchar(255), objetivo varchar(255), rif varchar(255), ubicacion varchar(255), fecha_fundacion date, PRIMARY KEY (id));
COMMENT ON TABLE Inmobiliaria IS 'Tabla donde se almacena la Inmobiliaria principal (una sola)';
COMMENT ON COLUMN Inmobiliaria.id IS 'id de la inmobiliaria';
COMMENT ON COLUMN Inmobiliaria.nombre IS 'Nombre de la inmobiliaria';
COMMENT ON COLUMN Inmobiliaria.mision IS 'Mision de la inmobiliaria';
COMMENT ON COLUMN Inmobiliaria.vision IS 'Visión de la inmobiliaria';
COMMENT ON COLUMN Inmobiliaria.objetivo IS 'Objetivo general de la inmobiliaria';
COMMENT ON COLUMN Inmobiliaria.rif IS 'Rif de la inmobiliaria';
COMMENT ON COLUMN Inmobiliaria.ubicacion IS 'Ubicación de la inmobiliaria';
COMMENT ON COLUMN Inmobiliaria.fecha_fundacion IS 'Fecha en que fue fundada la inmobiliaria';
CREATE TABLE Inmueble (id int4 NOT NULL, Servicioid int4 NOT NULL, ubicación varchar(255), fecha_construcción date, estatus char(255), Contratoid int4, PRIMARY KEY (id));
COMMENT ON TABLE Inmueble IS 'Tabla donde se almacenarán los inmuebles registrados, tanto en proceso de venta/alquiler/compra como ya finalizados';
COMMENT ON COLUMN Inmueble.id IS 'Id del inmueble';
COMMENT ON COLUMN Inmueble.ubicación IS 'Ubicación del inmueble';
COMMENT ON COLUMN Inmueble.fecha_construcción IS 'Fecha en que fue construido el inmueble';
COMMENT ON COLUMN Inmueble.estatus IS 'Estatus del inmueble';
CREATE TABLE Notificacion (id int4 NOT NULL, Citaid int4, Usuarioid int4, Promocionid int4, texto varchar(255), estatus char(255), PRIMARY KEY (id));
COMMENT ON TABLE Notificacion IS 'Notificaciones que se realizan en base al perfil del cliente, a las citas y las que genere el personal y/o cliente hacia el usuario.';
COMMENT ON COLUMN Notificacion.id IS 'Id de la notificación';
COMMENT ON COLUMN Notificacion.texto IS 'Texto de la notificación';
COMMENT ON COLUMN Notificacion.estatus IS 'Estatus de la notificación: activa, inactiva, leida, por leer, etc.';
CREATE TABLE PerfilCliente (Especificacionesid int4, Clienteid int4, cantidad int4);
COMMENT ON TABLE PerfilCliente IS 'Tabla que almacena las especificaciones/características que un cliente desea';
COMMENT ON COLUMN PerfilCliente.cantidad IS 'Cantidad si la especificación lo requiere: cantidad de baños, cuartos, etc.';
CREATE TABLE Personal (id int4 NOT NULL, Sucursalid int4, TipoPersonalid int4, nombres varchar(255), apellido varchar(255), correo varchar(255), telefono varchar(255), identificacion varchar(255), PRIMARY KEY (id));
COMMENT ON TABLE Personal IS 'Tabla donde se almacenarán todo los trabajadores de la inmobiliaria por sucursal. Agentes, recepcionistas, secretarias, etc.';
COMMENT ON COLUMN Personal.nombres IS 'Nombre del trabajador';
COMMENT ON COLUMN Personal.apellido IS 'Apellidos del trabajador';
COMMENT ON COLUMN Personal.correo IS 'Correo del trabajador';
COMMENT ON COLUMN Personal.telefono IS 'Teléfono del trabajador';
COMMENT ON COLUMN Personal.identificacion IS 'Rif o cédula del trabajador';
CREATE TABLE Promocion (id int4 NOT NULL, nombre varchar(255), descripcion varchar(255), estatus char(255), PRIMARY KEY (id));
COMMENT ON TABLE Promocion IS 'Tabla donde se almacenan las promociones que se realizan sobre los inmuebles: descuentos, regalos, etc.';
COMMENT ON COLUMN Promocion.id IS 'Id de la promoción';
COMMENT ON COLUMN Promocion.nombre IS 'Nombre de la promoción';
COMMENT ON COLUMN Promocion.descripcion IS 'Descripción de la promoción';
COMMENT ON COLUMN Promocion.estatus IS 'Estatus de la promoción';
CREATE TABLE PromocionesPorInmueble (Inmuebleid int4, Promocionid int4, estatus char(255));
COMMENT ON TABLE PromocionesPorInmueble IS 'Tabla que especifica que promoción está activa en un inmueble en particular';
COMMENT ON COLUMN PromocionesPorInmueble.estatus IS 'Estatus de la promoción en el inmueble';
CREATE TABLE Propietario (Clienteid int4, Inmuebleid int4 NOT NULL);
COMMENT ON TABLE Propietario IS 'Tabla que relaciona un cliente con su inmueble en caso de que sea propietario';
CREATE TABLE Rol (id int4 NOT NULL, nombre varchar(255), descripcion varchar(255), estatus char(255), PRIMARY KEY (id));
COMMENT ON TABLE Rol IS 'Tabla donde se almacenarán los roles que tiene un usuario en el sistema (seguridad funcional). Un rol está compuesto por funciones que puede ejecutar.';
COMMENT ON COLUMN Rol.id IS 'Id del rol';
COMMENT ON COLUMN Rol.nombre IS 'Nombre del rol';
COMMENT ON COLUMN Rol.descripcion IS 'Descripción del rol';
COMMENT ON COLUMN Rol.estatus IS 'Estatus del rol';
CREATE TABLE Servicio (id int4 NOT NULL, nombre varchar(255), descripcion varchar(255), Inmobiliariaid int4, estatus char(255), PRIMARY KEY (id));
COMMENT ON TABLE Servicio IS 'Tabla para codificar el tipo de servicio:
1- Alquiler
2- Venta
3- Compra';
COMMENT ON COLUMN Servicio.id IS 'ID del tipo de servicio';
COMMENT ON COLUMN Servicio.nombre IS 'Nombre del tipo de servicio';
COMMENT ON COLUMN Servicio.descripcion IS 'Descripción del tipo de servicio';
COMMENT ON COLUMN Servicio.estatus IS 'Estatus de la sucursal';
CREATE TABLE Sucursal (id int4 NOT NULL, Inmobiliariaid int4, rif varchar(255), ubicacion varchar(255), PRIMARY KEY (id));
COMMENT ON TABLE Sucursal IS 'Tabla donde se almacenan las sucursales de la inmobiliaria';
COMMENT ON COLUMN Sucursal.id IS 'ID de la sucursal';
COMMENT ON COLUMN Sucursal.rif IS 'Rif de la sucursal';
COMMENT ON COLUMN Sucursal.ubicacion IS 'Ubicación de la sucursal';
CREATE TABLE TipoCita (id int4 NOT NULL, nombre varchar(255) 		, descripcion varchar(255), estatus char(255), PRIMARY KEY (id));
COMMENT ON TABLE TipoCita IS 'Tabla donde se almacenan los tipos de cita: Solicitud de servicio, inspección, visita de inmueble, incidencia, etc.';
COMMENT ON COLUMN TipoCita.id IS 'Id del tipo de cita';
COMMENT ON COLUMN TipoCita.nombre IS 'Nombre del tipo de cita';
COMMENT ON COLUMN TipoCita.descripcion IS 'Descripción del tipo de cita';
COMMENT ON COLUMN TipoCita.estatus IS 'Estatus del tipo de cita';
CREATE TABLE TipoCliente (id int4 NOT NULL, nombre varchar(255), descripcion varchar(255), estatus char(255), PRIMARY KEY (id));
COMMENT ON TABLE TipoCliente IS 'Tabla donde se almacen los tipos de cliente: oferente y ofertante';
COMMENT ON COLUMN TipoCliente.id IS 'Id del tipo de cliente';
COMMENT ON COLUMN TipoCliente.nombre IS 'Nombre del tipo de cliente';
COMMENT ON COLUMN TipoCliente.descripcion IS 'Descripcion del tipo de cliente';
COMMENT ON COLUMN TipoCliente.estatus IS 'Estatus del tipo de cliente';
CREATE TABLE TipoEspecificacion (id int4 NOT NULL, nombre varchar(255), descripcion varchar(255), estatus char(255), PRIMARY KEY (id));
COMMENT ON TABLE TipoEspecificacion IS 'Tipo de especificación: de infrastructura, ubicación, diseño, etc.';
COMMENT ON COLUMN TipoEspecificacion.id IS 'Id del tipo de especificación';
COMMENT ON COLUMN TipoEspecificacion.nombre IS 'Nombre del tipo de especificación';
COMMENT ON COLUMN TipoEspecificacion.descripcion IS 'Descripción del tipo de especificación';
COMMENT ON COLUMN TipoEspecificacion.estatus IS 'Estatus del tipo de especificación';
CREATE TABLE TipoPersonal (id SERIAL NOT NULL, nombre varchar(255), descripcion varchar(255), PRIMARY KEY (id));
COMMENT ON TABLE TipoPersonal IS 'Tabla donde se almacenan los tipos de personal: agente, recepcionista, secretario,perito, etc.';
COMMENT ON COLUMN TipoPersonal.id IS 'Id del tipo de personal';
COMMENT ON COLUMN TipoPersonal.nombre IS 'Nombre del tipo de personal';
COMMENT ON COLUMN TipoPersonal.descripcion IS 'Descripcion del tipo de personal';
CREATE TABLE Usuario (id int4 NOT NULL, Clienteid int4, usuario varchar(255), contrasenna varchar(255), fecha_suscripcion date, Rolid int4, Personalid int4, PRIMARY KEY (id));
COMMENT ON TABLE Usuario IS 'Tabla donde se almacenarán los usuarios (credenciales) del sistema (móvil e intranet) indistintamente del rol que cumpla en la empresa (cliente o personal)';
COMMENT ON COLUMN Usuario.id IS 'Id del usuario';
COMMENT ON COLUMN Usuario.usuario IS 'Nombre de usuario (username) para las credenciales';
COMMENT ON COLUMN Usuario.contrasenna IS 'Contraseña del usuario (credenciales)';
COMMENT ON COLUMN Usuario.fecha_suscripcion IS 'Fecha en la que se realizó la suscripción';
CREATE UNIQUE INDEX Calificacion_id ON Calificacion (id);
CREATE UNIQUE INDEX Cita_id ON Cita (id);
CREATE UNIQUE INDEX Cliente_id ON Cliente (id);
CREATE INDEX Contrato_id ON Contrato (id);
CREATE UNIQUE INDEX Especificaciones_id ON Especificaciones (id);
CREATE UNIQUE INDEX Funciones_id ON Funciones (id);
CREATE UNIQUE INDEX Inmobiliaria_id ON Inmobiliaria (id);
CREATE UNIQUE INDEX Inmueble_id ON Inmueble (id);
CREATE UNIQUE INDEX Notificacion_id ON Notificacion (id);
CREATE UNIQUE INDEX Personal_id ON Personal (id);
CREATE UNIQUE INDEX Promocion_id ON Promocion (id);
CREATE UNIQUE INDEX Rol_id ON Rol (id);
CREATE UNIQUE INDEX Servicio_id ON Servicio (id);
CREATE UNIQUE INDEX Sucursal_id ON Sucursal (id);
CREATE UNIQUE INDEX TipoCita_id ON TipoCita (id);
CREATE UNIQUE INDEX TipoCliente_id ON TipoCliente (id);
CREATE UNIQUE INDEX TipoEspecificacion_id ON TipoEspecificacion (id);
CREATE UNIQUE INDEX TipoPersonal_id ON TipoPersonal (id);
CREATE INDEX Usuario_id ON Usuario (id);
ALTER TABLE Propietario ADD CONSTRAINT FKPropietari470681 FOREIGN KEY (Inmuebleid) REFERENCES Inmueble (id);
ALTER TABLE Funciones ADD CONSTRAINT FKFunciones792150 FOREIGN KEY (id_funcion_padre) REFERENCES Funciones (id);
ALTER TABLE Personal ADD CONSTRAINT FKPersonal664783 FOREIGN KEY (TipoPersonalid) REFERENCES TipoPersonal (id);
ALTER TABLE Personal ADD CONSTRAINT FKPersonal545393 FOREIGN KEY (Sucursalid) REFERENCES Sucursal (id);
ALTER TABLE Cita ADD CONSTRAINT FKCita795207 FOREIGN KEY (Servicioid) REFERENCES Servicio (id);
ALTER TABLE Notificacion ADD CONSTRAINT FKNotificaci142867 FOREIGN KEY (Citaid) REFERENCES Cita (id);
ALTER TABLE Notificacion ADD CONSTRAINT FKNotificaci444080 FOREIGN KEY (Promocionid) REFERENCES Promocion (id);
ALTER TABLE Notificacion ADD CONSTRAINT FKNotificaci74223 FOREIGN KEY (Usuarioid) REFERENCES Usuario (id);
ALTER TABLE Calificacion ADD CONSTRAINT FKCalificaci407706 FOREIGN KEY (Inmuebleid) REFERENCES Inmueble (id);
ALTER TABLE Calificacion ADD CONSTRAINT FKCalificaci871000 FOREIGN KEY (Personalid) REFERENCES Personal (id);
ALTER TABLE Calificacion ADD CONSTRAINT FKCalificaci80144 FOREIGN KEY (Clienteid) REFERENCES Cliente (id);
ALTER TABLE Cita ADD CONSTRAINT FKCita530927 FOREIGN KEY (Personalid) REFERENCES Personal (id);
ALTER TABLE PromocionesPorInmueble ADD CONSTRAINT FKPromocione905138 FOREIGN KEY (Promocionid) REFERENCES Promocion (id);
ALTER TABLE PromocionesPorInmueble ADD CONSTRAINT FKPromocione228592 FOREIGN KEY (Inmuebleid) REFERENCES Inmueble (id);
ALTER TABLE Contrato ADD CONSTRAINT FKContrato934942 FOREIGN KEY (Personalid) REFERENCES Personal (id);
ALTER TABLE Cita ADD CONSTRAINT FKCita67633 FOREIGN KEY (Inmuebleid) REFERENCES Inmueble (id);
ALTER TABLE Cita ADD CONSTRAINT FKCita740070 FOREIGN KEY (Clienteid) REFERENCES Cliente (id);
ALTER TABLE Cita ADD CONSTRAINT FKCita142988 FOREIGN KEY (TipoCitaid) REFERENCES TipoCita (id);
ALTER TABLE Usuario ADD CONSTRAINT FKUsuario30610 FOREIGN KEY (Clienteid) REFERENCES Cliente (id);
ALTER TABLE Usuario ADD CONSTRAINT FKUsuario178533 FOREIGN KEY (Personalid) REFERENCES Personal (id);
ALTER TABLE Usuario ADD CONSTRAINT FKUsuario38509 FOREIGN KEY (Rolid) REFERENCES Rol (id);
ALTER TABLE FuncionesPorRol ADD CONSTRAINT FKFuncionesP366641 FOREIGN KEY (Funcionesid) REFERENCES Funciones (id);
ALTER TABLE FuncionesPorRol ADD CONSTRAINT FKFuncionesP776509 FOREIGN KEY (Rolid) REFERENCES Rol (id);
ALTER TABLE PerfilCliente ADD CONSTRAINT FKPerfilClie530155 FOREIGN KEY (Especificacionesid) REFERENCES Especificaciones (id);
ALTER TABLE PerfilCliente ADD CONSTRAINT FKPerfilClie682451 FOREIGN KEY (Clienteid) REFERENCES Cliente (id);
ALTER TABLE Especificaciones ADD CONSTRAINT FKEspecifica349690 FOREIGN KEY (TipoEspecificacionid) REFERENCES TipoEspecificacion (id);
ALTER TABLE Cliente ADD CONSTRAINT FKCliente242548 FOREIGN KEY (TipoClienteid) REFERENCES TipoCliente (id);
ALTER TABLE Propietario ADD CONSTRAINT FKPropietari798243 FOREIGN KEY (Clienteid) REFERENCES Cliente (id);
ALTER TABLE EspecificacionesPorInmueble ADD CONSTRAINT FKEspecifica16238 FOREIGN KEY (Especificacionesid) REFERENCES Especificaciones (id);
ALTER TABLE EspecificacionesPorInmueble ADD CONSTRAINT FKEspecifica70308 FOREIGN KEY (Inmuebleid) REFERENCES Inmueble (id);
ALTER TABLE Inmueble ADD CONSTRAINT FKInmueble247920 FOREIGN KEY (Servicioid) REFERENCES Servicio (id);
ALTER TABLE Inmueble ADD CONSTRAINT FKInmueble34449 FOREIGN KEY (Contratoid) REFERENCES Contrato (id);
ALTER TABLE Contrato ADD CONSTRAINT FKContrato827504 FOREIGN KEY (Clienteid) REFERENCES Cliente (id);
ALTER TABLE Cliente ADD CONSTRAINT FKCliente889065 FOREIGN KEY (Sucursalid) REFERENCES Sucursal (id);
ALTER TABLE Sucursal ADD CONSTRAINT FKSucursal876515 FOREIGN KEY (Inmobiliariaid) REFERENCES Inmobiliaria (id);
ALTER TABLE Servicio ADD CONSTRAINT FKServicio796164 FOREIGN KEY (Inmobiliariaid) REFERENCES Inmobiliaria (id);
